name:       backspin
version:    0.1.0.0
github:     "gavinkflam/backspin"
license:    BSD3
author:     "Gavin Lam"
maintainer: "me@gavin.hk"
copyright:  "2018 Gavin Lam"

extra-source-files:
- README.md
- ChangeLog.md

description: >
  Please see the README on GitHub at <https://github.com/gavinkflam/backspin#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - array >= 0.5 && < 0.6
  - parsec >= 3.1 && < 3.2
  - mtl >= 2.2 && < 2.3

executables:
  backspin-exe:
    main:        Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backspin

tests:
  backspin-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backspin
